### PR TITLE
Fixed pdf exports in the budget module

### PR DESCRIPTION
**Pull request by anurag-ks**
Task - https://www.google-melange.com/gci/task/view/google/gci2014/5882396704505856
Please install Geraldo before testing.

### CODE REVIEW

**Comment by anurag-ks** [comment]
@hitesh96db please review

**Comment by hitesh96db** [comment]
Could you tell me how do I reproduce this ?
What does it fix ?

**Comment by anurag-ks** [comment]
On - /eden/budget/item and /eden/budget/item try to export the data as pdf.

**Comment by hitesh96db** [comment]
I'm unable to reproduce this bug...
Try it here: http://demo.sahanafoundation.org/eden/budget/item
Maybe it's fixed in trunk already ?

**Comment by anurag-ks** [comment]
@hitesh96db i doubting that would happen, uh nursix did pushed a commit which has disabled those functions, but the bugs are still there on enabling the functions
Here is the commit - https://github.com/flavour/eden/commit/59fecbf27a92635ae1e96fb6b21aec73794c0e21
Plus I also found out a todo that states that these functions should be modified to use s3pdf, but I think maybe S3PDF is being deprecated and we would be using s3export/codecs stuff. I wanted to know if I am correct, so i can start working on them in my next task.

**Comment by hitesh96db** [comment]
But on the demo site, If I try to export the data as pdf it works fine..

**Comment by anurag-ks** [comment]
Maybe the code for the demo site might have that commit by nursix which
diabled the custom export functions and is currently using the default one.

**Comment by anurag-ks** [comment]
@hitesh96db you can reproduce this by enabling those functions(if your
branch's HEAD is the same as flavour's) and then try to export them.

**Comment by ptressel** [comment]
Anurag, we made a little mistake with the staging branch, so I need to temporarily close all the PRs on it while we make a new staging.  I can still review your commit by itself.  When the new staging is ready, I'll post another comment and you can send the PR again.

**Comment by ptressel** [comment]
I'm going to try an experiment with your PR...  I have a "reopen" button, so I'm going to see what happens when I poke that.  The staging branch is different now -- a bunch of changes from trunk were reverted.  If GitHub re-computes the diff against the new staging, all should be well...

**Comment by anurag-ks** [comment]
@ptressel - Well that's alright, uh please review my work when your free

**Comment by ptressel** [comment]
So, Anurag and I just talked to Fran.  The functions these fixes are in are both going away.  Anurag has another thing to work on instead.  I'll close this so it won't be dangling from the staging branch.

**Pull request closed without merging**
