### PR TITLE
Moved import model to s3db/s3.py

### PR DESCRIPTION
**Pull request by anurag-ks**
Task - https://www.google-melange.com/gci/task/view/google/gci2014/5781419808784384
Todo - https://github.com/flavour/eden/blob/master/modules/s3/s3import.py#L1645

### CODE REVIEW

**Comment by anurag-ks** [comment]
If any change is required please don't mark the task as "Needs Work" because after 15 hours I won't be able to submit it again.

**Comment by ptressel** [comment]
What are you doing to test this?  Does the test suite run?  What would be some good "by hand" tests for this?

**Comment by ptressel** [comment]
Heh.  Run prepop.  That'll test it.  :D

**Comment by anurag-ks** [comment]
@ptressel done :+1:

**Pull request merged**
