### PR TITLE
 [GCI]Create a Template Task (With new template_location)

### PR DESCRIPTION
**Pull request by samsruti**
The Design is completed but there is some little css problems , which can fixed definitely.
Works fine for Chrome. But Some Css Problems are coming in Firefox
I want to make this template as a real deployment of sahana , so i will be working on these from April 2015.
But for this task , i think i completed all the features.
Link to GCI task : https://www.google-melange.com/gci/task/view/google/gci2014/5891812749213696
If anyone want to suggest something comment here : https://docs.google.com/document/d/1TBjs7X76mIQWrDe_RjUH8K0XHCDWXVIKe2qjU3LDJWc/edit?usp=sharing

### CODE REVIEW

**Comment by ramdesh** [comment]
Hi @samsruti, I tried to register but it says the register function is not implemented.

**Comment by samsruti** [comment]
Let me check

**Comment by samsruti** [comment]
WoW.. Now this is getting crashed in Mozilla and Chrome and also the register form is not working...
I dont know how this happened.

**Comment by ptressel** [comment]
We're chatting on IRC.  What we said there was:
1) Climate module has some bugs -- easy to fix but indicates it's not in working order.  Unless there's a real intent to use this, comment it out.
2) Better put in a tasks.cfg.

**Comment by ptressel** [comment]
We'll do a new PR with the CSS support for Firefox.

**Comment by ramdesh** [comment]
Merged from @samsruti for GCI Task https://www.google-melange.com/gci/task/view/google/gci2014/5891812749213696

**Comment by samsruti** [comment]
If anyone want to suggest something comment here : https://docs.google.com/document/d/1TBjs7X76mIQWrDe_RjUH8K0XHCDWXVIKe2qjU3LDJWc/edit?usp=sharing

I have added the todos for my template . I will be doing this after my BOARD exam (After April 2015)

**Pull request merged**
