### PR TITLE
Used os.walk to recurse into folders

### PR DESCRIPTION
**Pull request by DavidGrey**
@Nostraa @ptressel 

Sorry for the trouble. I was having issues with rebasing a commit, but I think everything is good now.

### CODE REVIEW

**Comment by DavidGrey** [comment]
Melange task: http://www.google-melange.com/gci/task/view/google/gci2014/5214672768729088

**Comment by DavidGrey** [comment]
@ptressel @Nostraa 

...I having been trying to close this one stupid little task for 10 days. 

I am ready to cry.

**Comment by hitesh96db** [comment]
Sorry for the delay :/

**Comment by DavidGrey** [comment]
Thanks you Hitesh :)

**Comment by DavidGrey** [comment]
@hitesh96db 

Frustratingly, while I was waiting for my task to be approved I conducted a usability test with a friend, but now there are none of those tasks left :(

**Comment by hitesh96db** [comment]
Some more tasks can be, and might be added soon, so it might not go waste :)
I hope you looked for other todos to work on...

**Comment by hitesh96db** [comment]
You were really patient compared to other students :)
Good Job :+1:

**Pull request merged**
