### PR TITLE
Default to logged in user for person in dc_collection

### PR DESCRIPTION
**Pull request by svineet**
Task: http://www.google-melange.com/gci/task/view/google/gci2014/5308941177192448

I wanted to do the root-org one too, but I don't know how to get the root org.

I tried to do the "elaborate" todo but I cannot find the create answer form, so I was not able to test it.

Also "auto-create answers on-accept" seems approachable but I'm afraid I do not understand how and what answers need to be created.

Can a mentor help me please? I'll be available on IRC almost all the time

### CODE REVIEW

**Comment by ramdesh** [comment]
Merging from @svineet for GCI Task http://www.google-melange.com/gci/task/view/google/gci2014/5308941177192448

**Comment by samsruti** [comment]
@ramdesh,  @ptressel please check this : https://github.com/flavour/eden/commit/21edfcf8259d8d9ebd0e727ee1dfb984b445e03a#diff-398f23d47f395892c1852a348fde3a4eR276

**Comment by ramdesh** [comment]
@samsruti, did you record this on the @ToDos sheet?

**Comment by svineet** [comment]
@samsruti I'm sorry I didn't know you had done these before since I did not see them done in the code. I didn't check the claim form because of the same reason, thinking if somebody would've done it already it would've been merged and would be in the code.

**Comment by samsruti** [comment]
Sorry i didn't mean that..

**Comment by samsruti** [comment]
Since dominic said,  this module is under experiment,  so i didn't add that todo

**Pull request merged**
