### PR TITLE
Many tickets fixed and Responsive Create Form for SSF Template for GCI Task

### PR DESCRIPTION
**Pull request by samsruti**
GCI Task : http://www.google-melange.com/gci/task/view/google/gci2014/5330074446331904
Sunflower Ticket :
1.  http://sunflower.sahanafoundation.org/eden/project/task/373/
2. http://sunflower.sahanafoundation.org/eden/project/task/348

And also the the create form is responsive.
All the form tables are responsive too.
By mistake i sent a pr to main repo : https://github.com/flavour/eden/pull/1035

### CODE REVIEW

**Comment by samsruti** [comment]
This also fixed this ticket also : http://sunflower.sahanafoundation.org/eden/project/task/348

**Comment by dklischies** [comment]
Datatables seem to be fixed, however the _create view isn't responsive. Please ensure that all the views you modifed become and/or stay responive.

**Comment by samsruti** [comment]
@ptressel or @ramdesh can any of please review my task ?

**Comment by ramdesh** [comment]
Merging from @samsruti for GCI Task http://www.google-melange.com/gci/task/view/google/gci2014/5330074446331904

**Pull request merged**
