### PR TITLE
[GCI]Create a Template Task (With new template_location)

### PR DESCRIPTION
**Pull request by samsruti**
The Design is completed but there is some little css problems , which can fixed definitely.
I want to make this template as a real deployment of sahana , so i will be working on these from April 2015.
But for this task , i think i completed all the features.
Link to GCI task : https://www.google-melange.com/gci/task/view/google/gci2014/5891812749213696

### CODE REVIEW

**Comment by ramdesh** [comment]
I merged in these changes, and receive the following error: 

Traceback (most recent call last):
  File "/home/ramindu/Projects/web2py/gluon/restricted.py", line 224, in restricted
    exec ccode in environment
  File "/home/ramindu/Projects/web2py/applications/gci_templates/models/zzz_1st_run.py", line 140, in <module>
    s3db.load_all_models()
  File "applications/gci_templates/modules/s3/s3model.py", line 340, in load_all_models
    cls.load(name)
  File "applications/gci_templates/modules/s3/s3model.py", line 317, in load
    model(name)
  File "applications/gci_templates/modules/s3/s3model.py", line 107, in **init**
    env = self.model()
  File "applications/gci_templates/modules/s3db/inv.py", line 1523, in model
    self.supply_item_represent,
  File "applications/gci_templates/modules/s3/s3model.py", line 163, in **getattr**
    AttributeError("undefined table: %s" % name))
  File "applications/gci_templates/modules/s3/s3model.py", line 251, in table
    raise default
AttributeError: undefined table: supply_item_represent

**Comment by samsruti** [comment]
but it's working fine in my system :(.  it's according to flavour main repo.

**Comment by robbyoconnor** [comment]
This task is still outstanding in [Melange](http://www.google-melange.com/gci/task/view/google/gci2014/5891812749213696)

**Comment by ramdesh** [comment]
Is the register() function not implemented?

**Pull request closed without merging**
